### ISSUE TITLE
Change Github repo main folder

### ISSUE THREAD

**Issue by kawa89** [andreskiu/weekday_selector_formfield#3]
It would be great if you could move the main folder so that when you enter your repo you will see a standard Github view:
<img width="600" alt="Zrzut ekranu 2020-04-10 o 09 13 35" src="https://user-images.githubusercontent.com/7292315/78971455-e7adb880-7b0b-11ea-88b5-e5f4273a7112.png">

instead of the current one:
<img width="600" alt="Zrzut ekranu 2020-04-10 o 09 13 25" src="https://user-images.githubusercontent.com/7292315/78971463-ec726c80-7b0b-11ea-88fe-966970e1a406.png">

**Comment by andreskiu** [comment]
Thanks, done!
I thought of having a folder with all the plugins, but in the end I did not organize it like that haha
